name:                backend
version:             0.1.0.0
github:              "githubuser/backend"
license:             BSD3
author:              "HitriyPapug"
maintainer:          "baklashov.ilya.ib@gmail.com"
copyright:           "2022 HitriyPapug"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/backend#readme>

default-extensions:
  - OverloadedStrings
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - DeriveGeneric
  - DeriveAnyClass  

dependencies:
- base >= 4.7 && < 5
- aeson
- conferer
- resourcet
- postgresql-simple
- transformers
- transformers-base
- http-types
- scotty
- smtp-mail
- text
- mtl
- regex-compat
- validation-selective
- uuid
- microlens
- uri-bytestring
- jwt
- bytestring
- containers
- time
- wai-cors

library:
  source-dirs: common
  exposed-modules: Common

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  auth:
    main:        Main.hs
    source-dirs: auth, common
    exposed-modules: Main
    other-modules: Database, Model, Common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2 
    - -ddump-simpl
    - -dsuppress-all 
    - -dno-suppress-type-signatures 
    - -ddump-to-file
  tasktracker:
    main:        Main.hs
    source-dirs: task-tracker, common
    exposed-modules: Main
    other-modules: Database, Model, Common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2 
    - -ddump-simpl
    - -dsuppress-all 
    - -dno-suppress-type-signatures 
    - -ddump-to-file



#tests:
#  backend-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - backend
